"""Remove unnecessary infomation

Revision ID: b88fd668a6a4
Revises: 
Create Date: 2025-01-24 19:54:31.624444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88fd668a6a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoros', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('custom_pomodoro_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=False,
               existing_server_default=sa.text('50'))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('custom_long_break_time')
        batch_op.drop_column('custom_short_break_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_short_break_time', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('custom_long_break_time', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('custom_pomodoro_time',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('50'))

    with op.batch_alter_table('pomodoros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
