"""Add new columns for Pomodoro model

Revision ID: ccdc46160817
Revises: b88fd668a6a4
Create Date: 2025-01-26 01:51:53.454955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdc46160817'
down_revision = 'b88fd668a6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pomodoros', schema=None) as batch_op:
        batch_op.drop_column('reason')
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
